"""Stage 3 — Code generation.

Consumes the PO-approved backlog and produces a draft pull request. When a
live LLM backend (Copilot bridge or Anthropic) is reachable, the module is
generated by the LLM with NatWest coding-standard constraints embedded in the
prompt. Otherwise a deterministic Flask scaffold is emitted. Each story
becomes one route + one handler with inline AC comments either way.
"""
from __future__ import annotations

import ast
import logging
import re

from ..integrations import MockClaudeClient, MockGitHubClient
from ..models import CodeFile, PullRequest, StoryBacklog, UserStory

logger = logging.getLogger(__name__)


def _slugify(text: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "_", text.lower()).strip("_")
    return slug or "feature"


def _render_handler(story: UserStory) -> str:
    fn = _slugify(story.want)
    criteria_comments = "\n".join(
        f"    # AC: {c}" for c in story.acceptance_criteria
    )
    return (
        f"@app.get('/{fn}')\n"
        f"def {fn}():\n"
        f"    # Story {story.id} — {story.as_a_statement}\n"
        f"{criteria_comments}\n"
        f"    # TODO: implement business logic against downstream services: "
        f"{', '.join(story.dependencies) or 'n/a'}\n"
        f"    return {{'status': 'ok', 'story': '{story.id}'}}\n"
    )


def _render_module(stories: list[UserStory], *, inject_defect: bool = False) -> str:
    header = (
        '"""Auto-generated by the SDLC Agent (Stage 3).\n\n'
        "Each handler corresponds to a single approved user story. Replace the\n"
        "TODO bodies with real implementations against existing repo patterns.\n"
        '"""\n'
        "import logging\n"
        "import os\n"
        "import requests\n"
        "from flask import Flask\n\n"
        "log = logging.getLogger(__name__)\n"
        "app = Flask(__name__)\n\n"
    )
    if inject_defect:
        # Demo-only seeded defects: violates NatWest TLS policy + uses print()
        # instead of the logger + embeds a hard-coded token. Stage 4 must flag
        # all three; Stage 3 remediation rerun emits the clean version.
        header += (
            "DOWNSTREAM_TOKEN = 'ghp_DEMO_HARDCODED_TOKEN_1234567890abcdef'\n"
            "\n"
            "def call_downstream(url):\n"
            "    print('calling', url)  # noqa: should use logger\n"
            "    return requests.get(url, verify=False, "
            "headers={'Authorization': DOWNSTREAM_TOKEN})\n\n"
        )
    return header + "\n\n".join(_render_handler(s) for s in stories)


def run(
    backlog: StoryBacklog,
    *,
    github: MockGitHubClient | None = None,
    claude: MockClaudeClient | None = None,
    inject_defect: bool = False,
) -> PullRequest:
    """Generate code for the approved backlog and open a draft PR.

    Args:
        backlog: PO-approved story backlog.
        github: GitHub client (mocked by default).
        claude: Claude client (mocked by default).
        inject_defect: Demo aid. When True, embeds seeded NatWest-standards
            violations so Stage 4 has something concrete to catch. The
            orchestrator's remediation loop re-runs Stage 3 with this set to
            False, modelling a real fix.
    """
    if not backlog.approved:
        raise RuntimeError(
            "Stage 3 invoked without PO approval. Run the approval gate first."
        )

    github = github or MockGitHubClient()
    claude = claude or MockClaudeClient()
    claude.complete(
        "stage3_code",
        {"stories": len(backlog.stories), "inject_defect": inject_defect},
    )

    backend = getattr(claude, "backend", "stub")
    logger.info(
        "Stage 3 starting (backend=%s, is_live=%s, inject_defect=%s)",
        backend, getattr(claude, "is_live", False), inject_defect,
    )

    module_path = f"src/{_slugify(backlog.brief_title)}.py"
    source = "rules"
    contents: str | None = None

    # Seeded-defect demo path stays deterministic so Stage 4 has known issues
    # to catch. Otherwise prefer the live LLM.
    if not inject_defect:
        contents = _generate_with_llm(backlog, module_path, claude)
        if contents is not None:
            source = "llm"

    if contents is None:
        contents = _render_module(backlog.stories, inject_defect=inject_defect)
        logger.info("Stage 3 used deterministic template (backend=%s).", backend)
    else:
        logger.info("Stage 3 used live LLM (backend=%s).", backend)

    files = [CodeFile(path=module_path, language="python", contents=contents)]

    branch = f"feature/{_slugify(backlog.brief_title)}"
    body_lines = [
        f"Implements {len(backlog.stories)} approved stories:",
        *(f"- {s.id}: {s.want}" for s in backlog.stories),
        "",
        "Generated by SDLC Agent (Phase 1, Claude Code).",
    ]
    # If a PR already exists for this branch (remediation rerun), overwrite
    # its files in place rather than opening a duplicate PR.
    for existing in github.pull_requests.values():
        if existing.branch == branch:
            github.add_files(existing.number, files)
            existing.files = list(files)
            existing.__dict__["_generation_source"] = source
            existing.__dict__["_generation_backend"] = backend
            return existing
    pr = github.open_pull_request(
        branch=branch,
        title=f"feat: {backlog.brief_title}",
        body="\n".join(body_lines),
        files=files,
        story_ids=[s.id for s in backlog.stories],
    )
    pr.__dict__["_generation_source"] = source
    pr.__dict__["_generation_backend"] = backend
    return pr


def _generate_with_llm(
    backlog: StoryBacklog, module_path: str, claude: MockClaudeClient
) -> str | None:
    """Ask the LLM to emit a single Python module for the backlog.

    Returns the file contents, or None if the LLM is unavailable / output is
    invalid. The caller is responsible for falling back to the template.
    """
    if not getattr(claude, "is_live", False):
        return None

    system = (
        "You are a senior NatWest backend engineer. Generate a single Python "
        "Flask module that implements the approved user stories. STRICT NatWest "
        "coding standards: use the standard `logging` module (never print); "
        "TLS verification MUST stay enabled (no verify=False); no hard-coded "
        "credentials, tokens or PII; no eval/exec; no shell=True; every public "
        "function has a docstring. Return STRICT JSON only — no prose, no "
        "markdown fences.\n\n"
        "Required implementation patterns (NOT optional, must appear in the code):\n"
        "1. Define a helper `_require_sso(req)` that reads the `Authorization` "
        "header, returns a principal dict on success, and aborts with HTTP 401 "
        "on missing/invalid token. Call it as the FIRST line of every route "
        "handler.\n"
        "2. For routes restricted to compliance / staff personas, also call "
        "`_require_role(principal, 'compliance')` (or the relevant role) and "
        "return HTTP 403 on mismatch.\n"
        "3. Any route that mutates state MUST use methods=['POST'] (or PUT/"
        "PATCH) — never GET — and MUST call `_audit(principal, action, "
        "details)` which logs an immutable audit entry via `logger.info` "
        "with action type, masked identifiers, timestamp (UTC), and a "
        "retention marker.\n"
        "4. Validate request JSON before use; return HTTP 400 on malformed "
        "input.\n"
        "5. One Flask route per story, route path derived from the story id. "
        "Inline `# AC:` comments mapping each acceptance criterion.\n"
        "6. Outbound HTTP calls (if any) must pass `timeout=` AND must "
        "explicitly pass `verify=True` (NatWest review standard requires "
        "explicit TLS verification, not the default).\n"
        "7. Implementations may leave business logic as a `# TODO` line, but "
        "the security/audit/method/validation scaffolding above must be real "
        "code, not TODOs."
    )
    schema_hint = (
        '{"path": "<module path>", "language": "python", '
        '"contents": "<full module source as one string>"}'
    )
    story_block = "\n\n".join(
        f"Story {s.id}\n"
        f"  As a {s.persona}, I want {s.want}, so that {s.so_that}.\n"
        f"  Dependencies: {', '.join(s.dependencies) or 'n/a'}\n"
        f"  Acceptance criteria:\n"
        + "\n".join(f"    - {c}" for c in s.acceptance_criteria)
        for s in backlog.stories
    )
    user = (
        f"Target file: {module_path}\n"
        f"Backlog title: {backlog.brief_title}\n\n"
        f"Approved stories:\n{story_block}\n\n"
        "Return JSON matching this shape exactly:\n"
        + schema_hint
    )

    data = claude.complete_json(
        system=system, user=user, max_tokens=4096, temperature=0.2
    )
    if not isinstance(data, dict):
        return None
    contents = data.get("contents")
    if not isinstance(contents, str) or "def " not in contents:
        return None

    # Defensive: reject any output that obviously breaks NatWest standards so
    # we fall back to the safe template rather than ship a non-compliant file.
    # Use the AST to ignore matches inside docstrings/comments/strings.
    try:
        tree = ast.parse(contents)
    except SyntaxError as exc:
        logger.warning("Stage 3 LLM output rejected: syntax error (%s).", exc)
        return None

    for node in ast.walk(tree):
        if isinstance(node, ast.Call):
            func = node.func
            # Reject real print() / eval() / exec() calls.
            if isinstance(func, ast.Name) and func.id in {"print", "eval", "exec"}:
                logger.warning(
                    "Stage 3 LLM output rejected: forbidden call %s().", func.id
                )
                return None
            # Reject verify=False or shell=True on any call.
            for kw in node.keywords:
                if kw.arg == "verify" and isinstance(kw.value, ast.Constant) and kw.value.value is False:
                    logger.warning("Stage 3 LLM output rejected: verify=False.")
                    return None
                if kw.arg == "shell" and isinstance(kw.value, ast.Constant) and kw.value.value is True:
                    logger.warning("Stage 3 LLM output rejected: shell=True.")
                    return None

    return contents
