"""Stage 6 — Deployment readiness.

Validates every release gate, drafts a release note, and emits the final
go/no-go decision.

Gates checked:
    * `tests_present`     — at least one test file in the PR
    * `review_passed`     — Stage 4 verdict == "pass"
    * `no_high_findings`  — no open HIGH/CRITICAL findings
    * `story_traceable`   — every PR story id traces back to backlog
"""
from __future__ import annotations

from ..integrations import MockClaudeClient, MockGitHubClient
from ..models import (
    DeploymentDecision,
    PullRequest,
    ReviewReport,
    StoryBacklog,
    TestSuite,
)


def _release_note(
    backlog: StoryBacklog, pr: PullRequest, tests: TestSuite
) -> str:
    lines = [
        f"## Release note — {backlog.brief_title}",
        "",
        f"PR #{pr.number} on branch `{pr.branch}`.",
        "",
        "### Stories delivered",
    ]
    lines.extend(f"- **{s.id}** {s.as_a_statement}" for s in backlog.stories)
    lines += [
        "",
        f"### Test coverage",
        f"{len(tests.files)} test file(s), "
        f"{sum(len(c.test_names) for c in tests.coverage_map)} tests mapped to "
        f"{len(tests.coverage_map)} acceptance criteria.",
        "",
        "_Generated by SDLC Agent — Phase 1 (Claude Code)._",
    ]
    return "\n".join(lines)


def run(
    pr: PullRequest,
    review: ReviewReport,
    tests: TestSuite,
    backlog: StoryBacklog,
    *,
    github: MockGitHubClient | None = None,
    claude: MockClaudeClient | None = None,
) -> DeploymentDecision:
    claude = claude or MockClaudeClient()
    claude.complete("stage6_deploy", {"pr": pr.number})

    backlog_ids = {s.id for s in backlog.stories}
    gates = {
        "tests_present": bool(tests.files),
        "review_passed": review.verdict == "pass",
        "no_high_findings": not review.high_or_critical,
        "story_traceable": all(sid in backlog_ids for sid in pr.story_ids),
    }
    blocking = [name for name, ok in gates.items() if not ok]
    go = not blocking

    if github is not None and go:
        github.set_state(pr.number, "ready")

    return DeploymentDecision(
        pr_number=pr.number,
        go=go,
        gates=gates,
        blocking_reasons=[f"Gate failed: {name}" for name in blocking],
        release_note=_release_note(backlog, pr, tests),
    )
